source = ./confs/input-laptop.conf
source = ./confs/env.conf
source = ./confs/execs.conf
source = ./confs/general.conf
source = ./confs/animations.conf
source = ./confs/decoration.conf
source = ./confs/windowrules.conf
source = ./confs/misc.conf
source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf
source = ./confs/custom.conf
